[window]
opacity = 0.80

[colors.primary]
background = "#26173E"
foreground = "#EFECF4"

[colors.cursor]
text = "#26173E"
cursor = "#94BA81"

[colors.vi_mode_cursor]
text = "#26173E"
cursor = "#94BA81"

[colors.search.matches]
foreground = "#26173E"
background = "#EAE43E"

[colors.search.focused_match]
foreground = "#26173E"
background = "#FF003C"

[colors.footer_bar]
foreground = "#26173E"
background = "#EFECF4"

[colors.selection]
text = "#94BA81"
background = "#EFECF4"

[colors.normal]
black = "#26173E"
red = "#FF003C"
green = "#94BA81"
yellow = "#EAE43E"
blue = "#46416A"
magenta = "#855E8D"
cyan = "#94BA81"
white = "#EFECF4"

[colors.bright]
black = "#554b67"
red = "#FF003C"
green = "#94BA81"
yellow = "#EAE43E"
blue = "#46416A"
magenta = "#855E8D"
cyan = "#fe4646"
white = "#EFECF4"
