# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#46FEEC"

# Title color for boxes
theme[title]="#FFFF4C"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ED4BA8"

# Background color of selected item in processes box
theme[selected_bg]="#DA11C9"

# Foreground color of selected item in processes box
theme[selected_fg]="#26173E"

# Color of inactive/disabled text
theme[inactive_fg]="#3D99CA"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#DA11C9"

# Box outline and divider line color
theme[cpu_box]="#ED4BA8"
theme[mem_box]="#FFFF4C"
theme[net_box]="#02B3F1"
theme[proc_box]="#DA11C9"
theme[div_line]="#28187D"

# Gradient for all meters and graphs
theme[temp_start]="#DA11C9"
theme[temp_mid]="#FFFF4C"
theme[temp_end]="#ED4BA8"

theme[cpu_start]="#02B3F1"
theme[cpu_mid]="#FFFF4C"
theme[cpu_end]="#ED4BA8"

theme[free_start]="#28187D"
theme[free_mid]="#02B3F1"
theme[free_end]="#DA11C9"

theme[cached_start]="#5A4ED6"
theme[cached_mid]="#02B3F1"
theme[cached_end]="#46FEEC"

theme[available_start]="#28187D"
theme[available_mid]="#02B3F1"
theme[available_end]="#DA11C9"

theme[used_start]="#02B3F1"
theme[used_mid]="#FFFF4C"
theme[used_end]="#ED4BA8"

theme[download_start]="#28187D"
theme[download_mid]="#02B3F1"
theme[download_end]="#46FEEC"

theme[upload_start]="#28187D"
theme[upload_mid]="#ED4BA8"
theme[upload_end]="#FFFF4C"
