# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#EFECF4"

# Title color for boxes
theme[title]="#EAE43E"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#FF003C"

# Background color of selected item in processes box
theme[selected_bg]="#EFECF4"

# Foreground color of selected item in processes box
theme[selected_fg]="#26173E"

# Color of inactive/disabled text
theme[inactive_fg]="#554B67"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#855E8D"

# Box outline and divider line color
theme[cpu_box]="#FF003C"
theme[mem_box]="#EAE43E"
theme[net_box]="#94BA81"
theme[proc_box]="#46416A"
theme[div_line]="#3E3633"

# Gradient for all meters and graphs
theme[temp_start]="#855E8D"
theme[temp_mid]="#f18902"
theme[temp_end]="#FF003C"

theme[cpu_start]="#94BA81"
theme[cpu_mid]="#EAE43E"
theme[cpu_end]="#FF003C"

theme[free_start]="#3E3633"
theme[free_mid]="#554B67"
theme[free_end]="#94BA81"

theme[cached_start]="#46416A"
theme[cached_mid]="#855E8D"
theme[cached_end]="#EFECF4"

theme[available_start]="#3E3633"
theme[available_mid]="#554B67"
theme[available_end]="#94BA81"

theme[used_start]="#94BA81"
theme[used_mid]="#f18902"
theme[used_end]="#FF003C"

theme[download_start]="#3E3633"
theme[download_mid]="#855E8D"
theme[download_end]="#EFECF4"

theme[upload_start]="#3E3633"
theme[upload_mid]="#f18902"
theme[upload_end]="#EAE43E"
