background = #26173E
foreground = #46FEEC
background-opacity = 0.80
background-blur = false
cursor-color = #46FEEC
selection-background = #ED4BA8
selection-foreground = #FFFF4C

palette = 0=#26173E
palette = 1=#FF003C
palette = 2=#1BD7F8
palette = 3=#EAE43E
palette = 4=#5A4ED6
palette = 5=#DA11C9
palette = 6=#02B3F1
palette = 7=#46FEEC
palette = 8=#3D99CA
palette = 9=#FF003C
palette = 10=#1BD7F8
palette = 11=#FFFF00
palette = 12=#5A4ED6
palette = 13=#B03DCE
palette = 14=#1BD7F8
palette = 15=#46FEEC
