background = #26173E
foreground = #EFECF4
background-opacity = 0.80
background-blur = false
cursor-color = #94BA81
selection-background = #EFECF4
selection-foreground = #EFECF4

palette = 0=#26173E
palette = 1=#FF003C
palette = 2=#94BA81
palette = 3=#EAE43E
palette = 4=#46416A
palette = 5=#855E8D
palette = 6=#94BA81
palette = 7=#EFECF4
palette = 8=#554b67
palette = 9=#FF003C
palette = 10=#94BA81
palette = 11=#EAE43E
palette = 12=#46416A
palette = 13=#855E8D
palette = 14=#fe4646
palette = 15=#EFECF4
