# hyprlock.conf
# Reze Theme (Chainsaw Man - Reze Arc)
#

$color = rgba(239, 236, 244, 1)
$inner_color = rgba(70, 65, 106, 0.66)
$outer_color = rgba(62, 54, 51, 1)
$font_color = rgba(239, 236, 244, 1)
$placeholder_color = rgba(133, 94, 141, 0.7)
$check_color = rgba(148, 186, 129, 1)