# hyprlock.conf
# Cyberpunk Edgerunners Theme
#

$color = rgba(255, 255, 76, 1)
$inner_color = rgba(255, 255, 76, 0.66)
$outer_color = rgba(40, 24, 125, 1)
$font_color = rgba(70, 254, 236, 1)
$placeholder_color = rgba(70, 254, 236, 0.7)
$check_color = rgba(218, 17, 201, 1)