foreground            #EFECF4
background            #26173E
background_opacity    0.80

selection_foreground  #EFECF4
selection_background #EFECF4
cursor                #94BA81
cursor_text_color     #26173E

active_border_color   #94BA81
active_tab_background #94BA81

color0 #26173E
color1 #FF003C
color2 #94BA81
color3 #EAE43E
color4 #46416A
color5 #855E8D
color6 #94BA81
color7 #EFECF4
color8 #554b67
color9 #FF003C
color10 #94BA81
color11 #EAE43E
color12 #46416A
color13 #855E8D
color14 #fe4646
color15 #EFECF4
