foreground            #46FEEC
background            #26173E
background_opacity    0.80

selection_foreground  #FFFF4C
selection_background #ED4BA8
cursor                #46FEEC
cursor_text_color     #26173E

active_border_color   #DA11C9
active_tab_background #DA11C9

color0 #26173E
color1 #FF003C
color2 #1BD7F8
color3 #EAE43E
color4 #5A4ED6
color5 #DA11C9
color6 #02B3F1
color7 #46FEEC
color8 #3D99CA
color9 #FF003C
color10 #1BD7F8
color11 #FFFF00
color12 #5A4ED6
color13 #B03DCE
color14 #1BD7F8
color15 #46FEEC
